{% set name = "imglyb" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ace14759bb4201e4b1b93ff4c4aa2c90e87e0bb22095160e205792be89fee929

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv  --no-deps
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - jpype1
    - scyjava >=1.3.0
  run:
    - python >=3.6
    - numpy
    - jpype1
    - scyjava >=1.3.0
    - maven

test:
  imports:
    - imglyb
    - imglyb.util

about:
  home: https://github.com/imglib/imglyb
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: A bridge between Numpy and imglib2
  doc_url: https://github.com/imglib/imglyb
  dev_url: https://github.com/imglib/imglyb

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
