{% set name = "imglyb" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9651860278bd4f05d74b47d7ea06df7f24e39cfbfb541208d913fbd01c48c276

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vvv  --no-deps
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy
    - jpype1 >=1.3.0
    - scyjava >=1.3.0
  run:
    - python >={{ python_min }}
    - numpy
    - jpype1 >=1.3.0
    - scyjava >=1.3.0
    - maven

test:
  requires:
    - python {{ python_min }}
  imports:
    - imglyb
    - imglyb.util

about:
  home: https://github.com/imglib/imglyb
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: A bridge between Numpy and imglib2
  doc_url: https://github.com/imglib/imglyb
  dev_url: https://github.com/imglib/imglyb

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
