{% set name = "imglyb" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34c745c79a60445455ccf902be97b93c6a5b2bd2c4f09911d58bda80964e8c6d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv  --no-deps"
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
    - numpy
    - pyjnius
    - scyjava
  run:
    - python
    - numpy
    - pyjnius
    - scyjava
    - maven

test:
  imports:
    - imglyb
    - imglyb.util

about:
  home: https://github.com/imglib/imglyb/
  license: PUBLIC-DOMAIN
  license_family: PUBLIC-DOMAIN
  summary: 'A bridge between Numpy and imglib2'
  doc_url: https://github.com/imglib/imglyb/
  dev_url: https://github.com/imglib/imglyb/

extra:
  recipe-maintainers:
    - ctrueden
    - hanslovsky
    - hadim
