{% set name = "imglyb" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdc3093a164b166c8cf3a1a74d72a32d7f0f6a640c5731ea48f6f741e92fc027

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv  --no-deps
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - jpype1
    - scyjava
  run:
    - python >=3.6
    - numpy
    - jpype1
    - scyjava
    - maven

test:
  imports:
    - imglyb
    - imglyb.util

about:
  home: https://github.com/imglib/imglyb
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: A bridge between Numpy and imglib2
  doc_url: https://github.com/imglib/imglyb
  dev_url: https://github.com/imglib/imglyb

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
