{% set name = "imglyb" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd86bad4c17390bdc2f11c85d4945dc73a3436d4bc2cbeefd95ed5db010f2961

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vvv  --no-deps"
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
    - numpy
    - pyjnius
    - scyjava
  run:
    - python
    - numpy
    - pyjnius
    - scyjava
    - maven

test:
  imports:
    - imglyb
    - imglyb.util

about:
  home: https://github.com/imglib/imglyb/
  license: PUBLIC-DOMAIN
  license_family: PUBLIC-DOMAIN
  summary: 'A bridge between Numpy and imglib2'
  doc_url: https://github.com/imglib/imglyb/
  dev_url: https://github.com/imglib/imglyb/

extra:
  recipe-maintainers:
    - ctrueden
    - hanslovsky
    - hadim
