{% set name = "imglyb" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ea65c43114c40b8fbdd6bab22bd78b8acbb2c3b6700c55fb4289ced59fef5c1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv  --no-deps
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - pyjnius
    - scyjava
  run:
    - python >=3.6
    - numpy
    - pyjnius
    - scyjava
    - maven

test:
  imports:
    - imglyb
    - imglyb.util

about:
  home: https://github.com/imglib/imglyb/
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: A bridge between Numpy and imglib2
  doc_url: https://github.com/imglib/imglyb/
  dev_url: https://github.com/imglib/imglyb/

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
