appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cZniMmrpeQF08DH+RYSpBf/93BqvN/SKk0fe7hlOlmdtgWiShY6azCicjh4nNgW70XvAMzcmkoshBzoHaLYtSLIRIfdOMnHt2FbtVINeQHubnjK6SGiDrkNpH9G7sqjmSg5AEdoeG33uTzcLAVE1LHnqDtRr0xfwmD9kAjrTCpDB6TylG2u+4QrVLUcLQaB1mDeF3+iR4Xga6vTwPZDEbznviaD0Wh2P/OYffnEFB0wPyBsPNlvlARsJN70f2acDT13ktAmvTYYCegQcdpVYYZNF660OZr60r5wgWB0GtG3emXrsQNst3xqoFfRw+UKCfrT3qMM3nXX9WuHNPw1EGPg/mHw1SMIBwlsc7f3OAJvd+xvpW9D4iJDLLcB6UOJGFbC8r6C2IkxSCfZdOh3aBoaZwJUGAkimBP8BzkiaGRXX3bYIBl0hqTxQPQy9t1wjpL+UEkb8Dpb6vP9AYQS1WFlvhDTzmMReDzqFHXTH7mRT5kWQ5kAans6MzDwsmvesGCsIUmTlWu3yFgZ5jIDt0q7laKFBuztVK6J7+Bww96HKqcz/RKJyP3aiPe6Yb5/nrPeVVAV1gKxt3wDu4w64oEswP0gWSnJlyItab3/2RsELOQ6Q4jZMtOGwglruUV4AtY0Bt5daDPFNd05f4eCBvWFnAIedO43jqDUmM3XSMr0=}
provider:
  win: azure
conda_forge_output_validation: true
